### PR TITLE
Update singularity-eos and singularity-opac

### PR DESCRIPTION
**Pull request by Yurlungur**
## PR Summary

This is only tested locally on my machine. @AstroBarker @mari2895 please check it works everywhere relevant, e.g., Chicoma.

Also, I currently point the `singularity-eos` submodule at [this branch](https://github.com/lanl/singularity-eos/pull/340). It needs to be updated once that PR goes through.

## PR Checklist

- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Format your changes by calling `scripts/bash/format.sh`.
- [ ] Explain what you did.

### CODE REVIEW

**Comment by AstroBarker** [comment]
Confirmed to build locally but seems to fail on Chicoma -- cmake could not locate the required hdf5 libraries in singularity.

**Comment by mari2895** [comment]
> Confirmed to build locally but seems to fail on Chicoma -- cmake could not locate the required hdf5 libraries in singularity.

Builds locally for me too.

**Comment by Yurlungur** [comment]
@AstroBarker @mari2895 this build appears to work with my instructions. Can you check for yourselves?

**Review by AstroBarker — APPROVED** [review]
LGTM! Now compiling and running successfully on Chicoma and locally.

**Review by mari2895 — APPROVED** [review]
compiles and runs for me

**Pull request merged**
