### PR TITLE
Merge homologouscollapse changes into main

### PR DESCRIPTION
**Pull request by mari2895**
## PR Checklist

- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Format your changes by calling `scripts/bash/format.sh`.
- [ ] Explain what you did.

### CODE REVIEW

**Comment by Yurlungur** [comment]
@mari2895 can you run the formatting script so the tests pass?

**Review by Yurlungur — APPROVED** [review]

**Review by carlnotsagan — APPROVED** [review]
LGTM

**Comment by mari2895** [comment]
@Yurlungur  did we not merge this?

**Comment by Yurlungur** [comment]
It looks like we implemented an alternative solution which is currently in main.

**Pull request closed without merging**
